spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: none

logging:
    level:
      ROOT: INFO